### ISSUE TITLE
Authenticator 4 Slots LUA Error

### ISSUE THREAD

**Issue by KronemeyerJoshua** [blooblahguy/bdBags#1]
New patch that introduced 4 additional bag slots for people with authenticators / SMS Protect.

LUA Error

`Message: ...terface\AddOns\Blizzard_TokenUI\Blizzard_TokenUI.lua:229: Usage: ContainerFrame1:SetHeight(height)
Time: 01/16/18 18:12:44
Count: 5
Stack: ...terface\AddOns\Blizzard_TokenUI\Blizzard_TokenUI.lua:229: Usage: ContainerFrame1:SetHeight(height)
[C]: ?
[C]: in function `SetHeight'
...terface\AddOns\Blizzard_TokenUI\Blizzard_TokenUI.lua:229: in function `ManageBackpackTokenFrame'
Interface\FrameXML\ContainerFrame.lua:284: in function `ContainerFrame_OnShow'
[string "*:OnShow"]:1: in function <[string "*:OnShow"]:1>
[C]: in function `Show'
Interface\AddOns\bdBags\core.lua:327: in function `Draw'
Interface\AddOns\bdBags\core.lua:403: in function `ContainerFrame_GenerateFrame'
Interface\FrameXML\ContainerFrame.lua:308: in function `OpenBag'
Interface\AddOns\bdBags\core.lua:421: in function `ToggleAllBags'
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals: `

**Comment by gladelynch** [comment]
This should be fixed in the latest bdBags build, not sure what changed in the patch but the global BACKPACK_HEIGHT doesn't exist for some reason. So I set it in my addon
